http_port 3128

pid_filename /tmp/squid.pid
visible_hostname egress-proxy

acl SSL_ports port 443
acl CONNECT method CONNECT
acl allowed_domains dstdomain "/tmp/allowed-domains.acl"

http_access deny !SSL_ports
http_access deny CONNECT !SSL_ports
http_access allow allowed_domains
http_access deny all

cache deny all
pinger_enable off
access_log stdio:/dev/stdout
cache_log stdio:/dev/stderr
coredump_dir /tmp
